# Generated by Django 5.2.15 on 2026-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueview",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
